### ISSUE TITLE
[Regression] Emulator freezes after some time while running a game (with trace)

### ISSUE THREAD

**Issue by FinishedFragment** [RPCS3/rpcs3#12415]
### Quick summary

No matter what game I play, there are now frequent freezes after say half an hour. Looking into the gdb output, I see a potential vital clue what went wrong:

```
Assertion '!m->thread || !pa_thread_is_running(m->thread) || !in_worker(m) || pa_atomic_load(&m->in_once_unlocked)' failed at ../pulseaudio/src/pulse/thread-mainloop.c:179, function pa_threaded_mainloop_lock(). Aborting.
```

### Details

[gdb.txt](https://github.com/RPCS3/rpcs3/files/9214825/gdb.txt)

OS: Arch Linux
Sound: PulseAudio

Other applications on my system which use sound work perfectly well, so I assume this might be an issue with the shipped cubeb (looking at the trace it looks like something something cubeb is accessing said function)? No idea how to debug this specific case tho.
In the two games I have tested (lightning returns and dark souls 2) I both use cubeb and both froze after some time.

```yaml
Audio:
  Renderer: Cubeb
  Audio Provider: CellAudio
  RSXAudio Avport: HDMI 0
  Dump to file: false
  Convert to 16 bit: false
  Audio Format: Stereo
  Audio Formats: 0
  Audio Device: "@@@default@@@"
  Master Volume: 100
  Enable Buffering: true
  Desired Audio Buffer Duration: 20
  Enable Time Stretching: false
  Time Stretching Threshold: 75
  Microphone Type: "Null"
  Microphone Devices: "@@@@@@@@@@@@"
  Music Handler: Qt
```

### Build with regression

Unknown. Maybe upstream?

### Attach two log files

n/a as the application freezes rather badly and does not get to write anything before crashing.
