### ISSUE TITLE
[Regression] Default Vulkan as video renderer

### ISSUE THREAD

**Issue by rtritto** [RPCS3/rpcs3#14205]
### Quick summary

Before #14153, the default video renderer was _Vulkan_

`config.yml`
```
Video:
  Renderer: Vulkan
  Vulkan:
    Adapter: <DEFAULT_GPU_NAME>
```
After, it's changed to _OpenGL_

`config.yml`
```
Video:
  Renderer: OpenGL
  Vulkan:
    Adapter: ""
```

### Build with regression

0.0.28-15335-e2c2ef97
